language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

services:
  - redis-server

before_script:
    - composer install
    - mysql -e 'create database mydb;'

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls